import 'dotenv/config';
import {QuestionCategoryEnum, RoomQuestion} from "../types";

export enum RolesTokens {
  front = 'i13.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcm9udCI6dHJ1ZX0.PGvYqU8t5D1iyOnMNmbGq2sisKtHez1arXLN5eXl4NU',
  corizoid = 'i13.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3Jpem9pZCI6dHJ1ZX0.ak3lllvOsDJIndsNzRIAtCCN_mPoS8p8xvcfZ_u40Fk',
}

export enum Roles {
  front = 'front',
  corizoid = 'corizoid',
}

export class Config {
  port: number;
  logger: {
    name: string;
    timeFormat: string;
  };
  promoCodeLiveTime: number;
  unprotectedRoutes: string[];
  questions: RoomQuestion[];
  corizoidToken: string;
  frontToken: string;
  corizoidUrl: string;
  redis: {
    host: string;
    port: number;
  };
}

const publicPartyText = 'Тут ти маєш можливість виграти призи. Тисни «Надіслати завдання», і воно прилетить одному з вас у @HomePartyBot. Виконай таск,  запости це в інсту й тегни сторінку @tuborgua. Готово. Тепер ти візьмеш участь у розіграші. Розіграш проводиться щонеділі наступного дня після вечірки. Переможця буде обрано за допомогою сервісу random.org., дивись результати на сторінці @tuborgua!Тисни ще раз, і хтось отримає нове завдання.';
const publicShowText = 'Тисни «Надіслати завдання», і воно прилетить одному з вас у @HomePartyBot. Нікому не кажи, що саме тобі прийшло – ти маєш показати це жестами так, щоб інші тусери точно відгадали. Щойно вгадають – тисни ще раз і грайте далі.';
const publicNeverText = 'Тисни «Надіслати “Я ніколи не...”», і фраза прилетить одному з вас у @HomePartyBot. Зачитай її вголос. Хто не робив цього в житті, нічого не робить і зараз. А хто робив – 🍺. Тисни знову, і один з вас отримає нову фразу.';
const publicTruthText = 'Тисни «Надіслати завдання», і воно прилетить одному з вас у @HomePartyBot. Ти отримаєш два таски: «правда» і «дія». Зачитай обидва вголос і вибери: розказати про себе правду чи виконати божевільну дію. Після виконання тисни ще раз і лови нове завдання в чиємусь @HomePartyBot.';

export const configInstance: Config = {
  redis: {
    host: process.env.REDIS_HOST,
    port: parseInt(process.env.REDIS_PORT_EXT || '6379', 10),
  },
  port: parseInt(process.env.API_PORT_EXT || '3000', 10),
  promoCodeLiveTime: 129600000, // 36h in ms
  frontToken: 'i13.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcm9udCI6dHJ1ZX0.PGvYqU8t5D1iyOnMNmbGq2sisKtHez1arXLN5eXl4NU',
  corizoidToken: 'i13.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3Jpem9pZCI6dHJ1ZX0.ak3lllvOsDJIndsNzRIAtCCN_mPoS8p8xvcfZ_u40Fk',
  unprotectedRoutes: [],
  logger: {
    name: 'Debug logs',
    timeFormat: 'HH:mm:ss ms'
  },
  questions: [
    {
      id: 0,
      questionSite: publicPartyText,
      questionChat: 'Зобрази з машиною будь-який мем.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 1,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся так, ніби тримаєш машину на руці.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 2,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини, танцюючи свій найбожевільніший танець.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 3,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини в стрибку.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 4,
      questionSite: publicPartyText,
      questionChat: 'Зобрази біля машини ганста-репера.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 5,
      questionSite: publicPartyText,
      questionChat: 'Зроби селфі зі смішним виразом обличчя на фоні машини.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 6,
      questionSite: publicPartyText,
      questionChat: 'Сфоткай свою спробу сісти на шпагат поруч із машиною.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 7,
      questionSite: publicPartyText,
      questionChat: 'Разом з другом/подругою зобразіть своїми тілами сердечко поруч із машиною.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 8,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини в позі зірки.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 9,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини, вдаючи Майкла Джексона.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 10,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини, роблячи «хвилю» руками.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 11,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини, сидячи біля неї, як чоткий типуля.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },
    {
      id: 12,
      questionSite: publicPartyText,
      questionChat: 'Сфоткайся біля машини, посилаючи повітряний поцілунок.',
      category: QuestionCategoryEnum.CATEGORY_1,
      used: false,
    },



    {
      id: 13,
      questionSite: publicShowText,
      questionChat: 'Патімейкер',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 14,
      questionSite: publicShowText,
      questionChat: 'Хайпожер',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 15,
      questionSite: publicShowText,
      questionChat: 'Диско-партизан',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 16,
      questionSite: publicShowText,
      questionChat: 'Двіж-бодряк',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 17,
      questionSite: publicShowText,
      questionChat: 'Гопник-інтроверт',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 18,
      questionSite: publicShowText,
      questionChat: 'ТікТокер',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 19,
      questionSite: publicShowText,
      questionChat: 'Т-Рекс',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 20,
      questionSite: publicShowText,
      questionChat: 'Качок',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 21,
      questionSite: publicShowText,
      questionChat: 'Фестиваль',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 22,
      questionSite: publicShowText,
      questionChat: 'Поп-діва',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 23,
      questionSite: publicShowText,
      questionChat: 'Обнімашки',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 24,
      questionSite: publicShowText,
      questionChat: 'Вайб',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 25,
      questionSite: publicShowText,
      questionChat: 'Брудні танці',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 26,
      questionSite: publicShowText,
      questionChat: 'Караоке',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 27,
      questionSite: publicShowText,
      questionChat: 'Охрана, отмєна!',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 28,
      questionSite: publicShowText,
      questionChat: 'Пивний патруль',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 29,
      questionSite: publicShowText,
      questionChat: 'Танцполтергейст',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 30,
      questionSite: publicShowText,
      questionChat: 'Рок-н-рольщик',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 31,
      questionSite: publicShowText,
      questionChat: 'Пельмень-канібал',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 32,
      questionSite: publicShowText,
      questionChat: 'Інспектор поганих жартів',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 33,
      questionSite: publicShowText,
      questionChat: 'Краля',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 34,
      questionSite: publicShowText,
      questionChat: 'Сусід',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 35,
      questionSite: publicShowText,
      questionChat: 'Ботан',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 36,
      questionSite: publicShowText,
      questionChat: 'Сомбреро',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 37,
      questionSite: publicShowText,
      questionChat: 'Тектонік',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 38,
      questionSite: publicShowText,
      questionChat: 'Лезгінка',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 39,
      questionSite: publicShowText,
      questionChat: 'Хор',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 40,
      questionSite: publicShowText,
      questionChat: 'Позитив',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 41,
      questionSite: publicShowText,
      questionChat: 'Саундтрек',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 42,
      questionSite: publicShowText,
      questionChat: 'Модниця',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 43,
      questionSite: publicShowText,
      questionChat: 'Дивак',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 44,
      questionSite: publicShowText,
      questionChat: 'Пристрасть',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 45,
      questionSite: publicShowText,
      questionChat: 'Нудьга',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 46,
      questionSite: publicShowText,
      questionChat: 'Святковий броненосець',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 47,
      questionSite: publicShowText,
      questionChat: 'Син маминої подруги',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 48,
      questionSite: publicShowText,
      questionChat: 'Морж',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 49,
      questionSite: publicShowText,
      questionChat: 'Задавака',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 50,
      questionSite: publicShowText,
      questionChat: 'Бомба-ракета',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 51,
      questionSite: publicShowText,
      questionChat: 'Прикол',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },
    {
      id: 52,
      questionSite: publicShowText,
      questionChat: 'Шаленство',
      category: QuestionCategoryEnum.CATEGORY_2,
      used: false,
    },



    {
      id: 53,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не засинав на паті.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 54,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не цілувався ні з ким із присутніх.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 55,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не робив еротичних селфі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 56,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не розповідав чужих секретів.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 57,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не вдягав одяг протилежної статі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 58,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не брехав своєму партнерові.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 59,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не напивався сам.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 60,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не танцював стриптиз.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 61,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не робив татуювання.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 62,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи ні за ким не підглядав.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 63,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не виходив з дому без спідньої білизни.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 64,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не вдягав сланці зі шкарпетками.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 65,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не плакав під час перегляду фільму.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 66,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не рився в чужих речах або в телефоні.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 67,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не пропонував нікому нічого непристойного.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 68,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не був на побаченнях з двома різними людьми в один день.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 69,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не знайомився через додатки для знайомств.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 70,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не фантазував ні про кого з присутніх.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 71,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не зустрічався з кимось більше року.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 72,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не співав у душі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 73,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не варив борщу.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 74,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не водив машину.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 75,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не був у дитячому таборі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 76,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не співав у душі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 77,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не ходив у похід.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 78,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не вмочував картоплю фрі в морозиво чи мілкшейк.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 79,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не мав домашніх тварин.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 80,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не сходився знову з колишніми.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 81,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не бачив нікого з присутніх голим.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 82,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не засинав у громадських місцях.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 83,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не фліртував на роботі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 84,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не брав участі в бійках.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 85,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не знайомився на вулиці.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 86,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не брехав про свій вік.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 87,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не прогулював роботу.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 88,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не цілувався на першому побаченні.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 89,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не був у стрип-клубі.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 90,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не вигадував коктейлів.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },
    {
      id: 91,
      questionSite: publicNeverText,
      questionChat: 'Я ніколи не купував нічого в секонд-хенді.',
      category: QuestionCategoryEnum.CATEGORY_3,
      used: false,
    },



    {
      id: 92,
      questionSite: publicTruthText,
      questionChat: `Питання: За який вчинок тобі найбільше соромно?\nДія: Зроби масаж голови будь-кому з учасників. `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 93,
      questionSite: publicTruthText,
      questionChat: `Питання: Кого з присутніх ти б взяв/ла з собою на безлюдний острів?\nДія: Візьми в гравця ліворуч будь-який предмет одягу й одягни на себе. `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 94,
      questionSite: publicTruthText,
      questionChat: `Питання: З ким і як відбувся твій перший поцілунок?\nДія: Винеси сміття просто зараз. `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 95,
      questionSite: publicTruthText,
      questionChat: `Питання: Що тебе дратує в найкращій подрузі?\nДія: Сядь на коліна будь-кому з компанії.  `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 96,
      questionSite: publicTruthText,
      questionChat: `Питання: Кого з присутніх ти вважаєш найпривабливішим?\nДія: Намалюй собі вуса зубною пастою.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 97,
      questionSite: publicTruthText,
      questionChat: `Питання: Яке було найгірше побачення у твоєму житті?\nДія: Спародіюй будь-кого з присутніх.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 98,
      questionSite: publicTruthText,
      questionChat: `Питання: Кого з присутніх ти б рятував/ла останнім під час катастрофи?\nДія: Стрибай на одній нозі, співаючи «Охрана, отмєна».`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 99,
      questionSite: publicTruthText,
      questionChat: `Питання: Що тобі найбільше подобається в собі?\nДія: Прочитай уголос останнє SMS-повідомлення.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 100,
      questionSite: publicTruthText,
      questionChat: ` Питання: Яка твоя найзаповітніша мрія?\nДія: Надкуси цілу цибулину, лимон або перець чилі.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 101,
      questionSite: publicTruthText,
      questionChat: `Питання: Спиш або ходиш по дому голяка?\nДія: Зображуй мавпочку протягом 5 хвилин.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 102,
      questionSite: publicTruthText,
      questionChat: `Питання: Розкажи про своє перше побачення.\nДія: Станцюй тверк просто зараз.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 103,
      questionSite: publicTruthText,
      questionChat: `Питання: Яке було твоє перше враження про людину ліворуч від тебе?\nДія: Придумай кожному з присутніх прізвисько, яке його характеризує.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 104,
      questionSite: publicTruthText,
      questionChat: `Питання: Яка риса тебе найбільше бісить у людях?\nДія: Вхопи людину праворуч за ніс.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 105,
      questionSite: publicTruthText,
      questionChat: `Питання: З ким із присутніх ти б хотів/ла залишитися сам на сам?\nДія: Поцілуй руку людині ліворуч.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 106,
      questionSite: publicTruthText,
      questionChat: `Питання: Який твій найбезглуздіший вчинок?\nДія: Вкуси себе або будь-кого з присутніх за ногу.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 107,
      questionSite: publicTruthText,
      questionChat: `Питання: Яка твоя найтемніша потаємна фантазія?\nДія: Вдягни весь свій одяг навиворіт і не перевдягайся до кінця гри.  `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },{
      id: 108,
      questionSite: publicTruthText,
      questionChat: `Питання: Розкажи смішну історію зі свого минулого. \nДія: Станцюй танго з будь-ким із присутніх.  `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 109,
      questionSite: publicTruthText,
      questionChat: `Питання: Ти коли-небудь цілувався/лась з людиною своєї статі? \nДія: Прочитай уголос переписку з будь-ким із присутніх.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 110,
      questionSite: publicTruthText,
      questionChat: ` Питання: Як би ти витратив/ла мільйон доларів? \nДія: Голосно гавкай у відчинене вікно протягом хвилини.  `,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 111,
      questionSite: publicTruthText,
      questionChat: `Питання: Назви 3 речі, у любові до яких тобі соромно зізнатись. \nДія: Покажи всім присутнім 10 останніх фото на твоєму телефоні.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 112,
      questionSite: publicTruthText,
      questionChat: `Питання: Кого б ти поцілував/ла просто тут і зараз?\nДія: Зроби 15 присідань.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 113,
      questionSite: publicTruthText,
      questionChat: `Питання: Чиї думки з присутніх хотів/ла б прочитати?\nДія: Зобрази диявольський сміх.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 114,
      questionSite: publicTruthText,
      questionChat: `Питання: У скільки років був твій перший секс?\nДія: Випий столову ложку соняшникової олії.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 115,
      questionSite: publicTruthText,
      questionChat: `Питання: Тобі колись снився хтось із присутніх? Якщо так, то хто?\nДія: Скажи комплімент кожному з присутніх.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 116,
      questionSite: publicTruthText,
      questionChat: `Питання: Кого з присутніх ти б взяв/ла в рабство?\nДія: Станцюй танець живота.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 117,
      questionSite: publicTruthText,
      questionChat: `Питання: Закохувався/лась таємно в подругу/друга?\nДія: Проспівай абетку, не розтуляючи рота.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 118,
      questionSite: publicTruthText,
      questionChat: `Питання: Про що найчастіше обманюєш?\nДія: Зобрази пантоміму.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 119,
      questionSite: publicTruthText,
      questionChat: `Питання: Яка для тебе максимально прийнятна різниця у віці, щоб бути в стосунках?\nДія: Понюхай усіх присутніх і скажи, хто найкраще пахне.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 120,
      questionSite: publicTruthText,
      questionChat: `Питання: Ти хропеш уві сні?\nДія: Дай п’ять кожному з присутніх.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 121,
      questionSite: publicTruthText,
      questionChat: `Питання: Оціни зовнішність і характер людини навпроти.\nДія: Пройдись місячною ходою через кімнату.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 122,
      questionSite: publicTruthText,
      questionChat: `Питання: Хто з гравців найбільше схожий на ідеал для гарних стосунків?\nДія: Станцюй макарену.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 123,
      questionSite: publicTruthText,
      questionChat: `Питання: Який тип білизни ти носиш?\nДія: Поцілуй у щічку кожного з присутніх.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 124,
      questionSite: publicTruthText,
      questionChat: `Питання: Коли востаннє в тебе був секс?\nДія: Зроби елемент одягу з туалетного паперу й носи його 15 хвилин.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 125,
      questionSite: publicTruthText,
      questionChat: `Питання: Чи є щось, про що навіть зараз не розказав би батькам? Що це?\nДія: Стій у кутку протягом 3 хвилин.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 126,
      questionSite: publicTruthText,
      questionChat: `Питання: На яке питання найменше хотілось би відповідати?\nДія: Говори з акцентом протягом наступних 10 хвилин.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 127,
      questionSite: publicTruthText,
      questionChat: `Питання: Коли-небудь мав/ла віртуальний секс або секс по телефону?\nДія: Стрибай якнайвище протягом хвилини.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 128,
      questionSite: publicTruthText,
      questionChat: `Питання: Який твій найдикіший вчинок сп’яну?\nДія: Спробуй жонглювати 3-ма речами.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 129,
      questionSite: publicTruthText,
      questionChat: `Питання: Скільки партнерів у тебе було?\nДія: Дозволь гравцю навпроти нафарбувати тобі губи.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 130,
      questionSite: publicTruthText,
      questionChat: `Питання: Яка шкідлива звичка в тебе з дитинства?\nДія: Набери в рот води й проспівай цілу пісню.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
    {
      id: 131,
      questionSite: publicTruthText,
      questionChat: `Питання: Що тобі не подобається в людині ліворуч і в людині праворуч від тебе?\nДія: Зроби смішний вираз обличчя та зберігай його протягом 2 хвилин.`,
      category: QuestionCategoryEnum.CATEGORY_4,
      used: false,
    },
  ],
  corizoidUrl: 'https://www.corezoid.com/api/1/json/public/770177/90931a17fce68d55f6ae19841c12f5ff29623fc1',
};
